---
title: "Table X. Reporting patterns"
output:
  word_document:
    reference_docx: word_style_template_01.docx
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_packages, message=FALSE, echo=FALSE, warning=FALSE}
# Load packages
library(tidyverse)
library(feather)

source("../../R/label_qtext.R")
```

<!-- Load data -->

<!-- medstar_detect_demo.feather was created in data_clean_medstar.Rmd     -->
<!-- medstar_detect.feather was created in data_clean_medstar.Rmd    -->
<!-- merged_screening_recode.RData was created in preprocess_for_analysis.Rmd    -->

```{r echo=FALSE}
medstar_dd <- read_feather("/Users/bradcannell/Desktop/medstar_detect_demo.feather")
medstar_d  <- read_feather("/Users/bradcannell/Desktop/medstar_detect.feather")
merged_sr  <- read_rds("/Users/bradcannell/Desktop/merged_screening_recode.RData")
```

<!-- Data management -->

<!-- Currently, each row is an allegation. And, there can be multiple allegations per APS investigation. Each allegation has its own disposition. So, there can be multiple dispositions associated with an item for which "yes" was selected.  -->

<!-- Select just the vars I need -->

<!-- Create new variables for reported, any valid, any not valid, any unable to determine or other -->

```{r echo=FALSE}
screening_disposition <- merged_sr %>% 
  select(response_num, first_name, unusual_odor36:adls61, disposition) %>%  # Select vars of interest
  mutate(
    reported = 1,
    disposition = case_when(
      disposition == "Unable to Determine" ~ "Other",                       # Recode other
      disposition == "Other"               ~ "Other",
      TRUE                                 ~ disposition %>% as.character()
    )
  ) %>% 
  group_by(response_num, first_name) %>% 
  mutate(
    any_valid         = if_else(any(disposition == "Valid"),   1L, 0L),     # Create any / all vars
    all_invalid       = if_else(all(disposition == "Invalid"), 1L, 0L),
    disposition_other = if_else(any_valid == 0 & all_invalid == 0, 1L, 0L)
  ) %>% 
  ungroup() %>% 
  group_by(response_num, first_name) %>% 
  mutate(obs = row_number()) %>% 
  filter(obs == 1) %>%                                                      # Keep one row per response/name
  select(response_num, first_name, reported, any_valid, all_invalid, disposition_other)
```

<!-- For each screening item, create a new variable equal to 1 if "yes" was selected and 0 otherwise -->

```{r echo=FALSE}
yes_responses <- medstar_d %>% 
  select(unusual_odor36:adls61) %>% 
  mutate_all(
    funs(
      yes = case_when(. == "Yes" ~ 1L, TRUE ~ 0L) # 1 if Yes, 0 if anything else - including NA
    )
  )
```

<!-- Merge yes responses back with response number, date, and first name -->

```{r echo=FALSE}
id_date_name <- medstar_d %>% select(response_num, response_date, first_name)

yes_responses <- bind_cols(id_date_name, yes_responses)
```

<!-- Merge yes responses with disposition data -->

```{r echo=FALSE, warning=FALSE}
yes_responses <- yes_responses %>% 
  left_join(screening_disposition, by = c("response_num", "first_name")) %>% 
  mutate(reported = if_else(is.na(reported), 0, reported))
```

<!-- Make sure there are still 46 reports to APS -->

```{r include=FALSE}
# yes_responses %>%
#   group_by(response_num, first_name) %>%
#   mutate(count = row_number()) %>%
#   filter(count == 1) %>%
#   ungroup() %>%
#   summarise(Reports = sum(reported, na.rm = TRUE)) # 46
```









<!-- Create table shell -->

```{r echo=FALSE}
table <- tibble(
  Item                 = vector(mode = "character"),
  Reported             = vector(mode = "character"),
  `Reported - Valid`   = vector(mode = "character"),
  `Reported - Invalid` = vector(mode = "character"),
  `Reported - Other`   = vector(mode = "character")
)
```

<!-- Add stat identifier to table -->

```{r echo=FALSE}
table[1, ] <- c("", rep("N (%)", 4))
```

<!-- Create function to return N and percent reported, reported and valid, reported and invalid, and reported and other - for each screening item -->

```{r echo=FALSE}
# For data checking - if needed
# yes_responses %>%
#   filter(unusual_odor36_yes == 1) %>%
#   summarise(
#     yes                  = nrow(.),
#     reported             = sum(reported),
#     reported_percent     = ((reported / yes) * 100) %>% round(1) %>% format(nsmall = 1L),
#     Reported             = paste0(reported, " (", reported_percent, ")"),
# 
#     rv                   = sum(any_valid == 1, na.rm = TRUE),
#     rv_percent           = ((rv / reported) * 100) %>% round(1) %>% format(nsmall = 1L),
#     `Reported - Valid`   = paste0(rv, " (", rv_percent, ")"),
# 
#     ri                   = sum(all_invalid == 1, na.rm = TRUE),
#     ri_percent           = ((ri / reported) * 100) %>% round(1) %>% format(nsmall = 1L),
#     `Reported - Invalid` = paste0(ri, " (", ri_percent, ")"),
# 
#     ro                   = sum(disposition_other == 1, na.rm = TRUE),
#     ro_percent           = ((ro / reported) * 100) %>% round(1) %>% format(nsmall = 1L),
#     `Reported - Other`   = paste0(ro, " (", ri_percent, ")")
#   )
```

```{r echo=FALSE}
count_reported_by_disposition <- function(df, column) {
  
  # append yesto end of var name and convert to quoture
  item <- enquo(column)
  yes  <- paste(quo_name(item), "yes", sep = "_") %>% rlang::sym()

  yes_responses %>% 
    filter(rlang::UQ(yes) == 1) %>% 
    
    summarise(
      yes                  = nrow(.),
      reported             = sum(reported),
      reported_percent     = ((reported / yes) * 100),
      reported_percent     = if_else(is.nan(reported_percent), 0, reported_percent) %>% 
                             round(1) %>% format(nsmall = 1L),
      Reported             = paste0(reported, " (", reported_percent, ")"),
    
      rv                   = sum(any_valid == 1, na.rm = TRUE),
      rv_percent           = ((rv / reported) * 100),
      rv_percent           = if_else(is.nan(rv_percent), 0, rv_percent) %>% 
                             round(1) %>% format(nsmall = 1L),
      `Reported - Valid`   = paste0(rv, " (", rv_percent, ")"),
    
      ri                   = sum(all_invalid == 1, na.rm = TRUE),
      ri_percent           = ((ri / reported) * 100),
      ri_percent           = if_else(is.nan(ri_percent), 0, ri_percent)  %>% 
                             round(1) %>% format(nsmall = 1L),
      `Reported - Invalid` = paste0(ri, " (", ri_percent, ")"),
    
      ro                   = sum(disposition_other == 1, na.rm = TRUE),
      ro_percent           = ((ro / reported) * 100),
      ro_percent           = if_else(is.nan(ro_percent), 0, ro_percent) %>% 
                             round(1) %>% format(nsmall = 1L),
      `Reported - Other`   = paste0(ro, " (", ri_percent, ")")  
      
    ) %>% 
    mutate(Item = !!quo_name(item)) %>% 
    select(Item, Reported, `Reported - Valid`, `Reported - Invalid`, `Reported - Other`)

}
# count_reported_by_disposition(response_counts, unusual_odor36)
```

<!-- Loop over all screening items -->

```{r echo=FALSE}
all_items <- medstar_d %>%                                                      # Select all screening items
  select(unusual_odor36:adls61) %>% 
  names()

row <- 2                                                                        # Row index to start with
columns <- 1:5                                                                  # Columns to fill in

for(i in seq_along(all_items)) {                                                # Loop over each screening item
  item <- rlang::sym(all_items[[i]])                                            # To "unquote" the column names
  table[row, columns] <- count_reported_by_disposition(response_counts, !!item) # Fill in table
  row <- row + 1                                                                # Increment row
}
```

<!-- Add screening item text to "item" column -->\

```{r echo=FALSE}
table[2:27, 1] <- label_qtext()
```

<!-- Turn into Kable -->

```{r, echo=FALSE, message=FALSE, warning=FALSE}
table_reporting_patterns_kable <- knitr::kable(table)
write_rds(table_reporting_patterns_kable, path = "table_reporting_patterns_kable.rds") # Save
table_reporting_patterns_kable
```

```{r notes, include=FALSE}
# After knitting word table:
# Reorient to landscape
# Change all font to TNR 11
# Remove bold from title - except "Table 1"
# Center rows 1 & 2
# Adjust column widths as needed
# Add bottom border to table
```
























